# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c98dc98b9ffc6222bb2758229b477be743dd11ba14c0a46d895c9a55614a711bdd2b01879c0687ef1c7683776731fadaf6f704b29d1228109bc90e187a96955

test:
  secret_key_base: 928faf70d37f3368189bc1673d8dda18cb83c4fb66ad31803277ff34dc4de0ddddfca842afa49e62708626a4c2a531a5bef92dc4bcbe2d917e7ab57670c5c3d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
